version: '3.8'

services:
  catalog.api:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_URLS=http://+:80
    ports:
      - 5111:80
    networks:
      - webnet

  nginx:

    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
